export default [
    "Aragorn",
    "Arwen",
    "Bilbo Baggins",
    "Frodo Baggins",
    "Barliman Butterbur",
    "Beechbone",
    "Beregond",
    "Bergil",
    "Fredegar Bolger",
    "Tom Bombadil",
    "Boromir",
    "Meriadoc Brandybuck",
    "Bregalad",
    "Celeborn",
    "Círdan",
    "Déagol",
    "Denethor",
    "Dúnhere",
    "Elfhelm",
    "Elladan",
    "Elrohir",
    "Elrond",
    "Éomer",
    "Éomund",
    "Éothain",
    "Éowyn",
    "Erestor",
    "Erkenbrand",
    "Faramir",
    "Forlong",
    "Galadriel",
    "Hamfast Gamgee",
    "Samwise Gamgee",
    "Gamling",
    "Gandalf",
    "Gildor Inglorion",
    "Gimli",
    "Glorfindel",
    "Goldberry",
    "Gollum",
    "Gothmog",
    "Gríma Wormtongue",
    "Grimbold",
    "Haldir of Lórien",
    "Háma",
    "Húrin the Tall",
    "Isildur",
    "Legolas",
    "Farmer Maggot",
    "Mouth of Sauron",
    "Nazgûl",
    "Old Man Willow",
    "Orophin",
    "Radagast",
    "Saruman",
    "Sauron",
    "Shelob",
    "Théoden",
    "Théodred",
    "Peregrin Took",
    "Treebeard",
    "Witchking of Angmar",
]
